Authing/Guard

- public/index.html
- src/main.js
- src/views/Authorize.vue
- src/views/Login.vue
> Feature oidc

- src/main.js
- src/views/regedit/regedit.vue
- src/views/teaIdentity/teaIdentity.vue
> 成功提示，修改用户头像使用方式

- src/main.js
- src/store/modules/protocol.js
- src/views/Authorize.vue
- src/views/Profile.vue
- src/views/login/PhoneLogin.vue
- src/views/regedit/regedit.vue
- src/views/simple/PhoneLogin.vue
- src/views/teaIdentity/teaIdentity.vue
跳转登录添加，隐私协议，手机验证码页面修改，教师认证页面图片问题修改，邮箱正则修改
> 跳转登录，隐私协议，手机验证码页面，教师认证页面图片，邮箱正则

- src/views/regedit/regedit.vue
- src/views/teaIdentity/teaIdentity.vue
> regedit选择学校改成和教师认证一样

- public/index.html
修复默认开发模式下的 URL 值错误问题。
同时调整 EndpointSwitch 变量作用域
> fix: update backend uri

- examples/guard-angular/package-lock.json
- examples/guard-angular/package.json
- examples/guard-angular/src/app/app.component.css
- examples/guard-angular/src/app/app.module.ts
- examples/guard-react/package-lock.json
- examples/guard-react/package.json
- examples/guard-react/src/App.tsx
- examples/guard-react/webpack.config.js
- examples/guard-vue2/package-lock.json
- examples/guard-vue2/package.json
- examples/guard-vue2/src/main.js
- examples/guard-vue2/src/views/Personal.vue
- examples/guard-vue3/package-lock.json
- examples/guard-vue3/package.json
- examples/guard-vue3/src/main.ts
- examples/guard-vue3/src/views/Personal.vue
- examples/guard/package-lock.json
- examples/guard/package.json
- examples/guard/src/App.tsx
- examples/guard/src/pages/Callback.tsx
- examples/guard/src/pages/Jump.tsx
- examples/guard/src/pages/Login.tsx
- examples/guard/src/pages/Personal.tsx
> test: guard subpackages, 5.0.0-alpha.11

- examples/guard-angular/package-lock.json
- examples/guard-angular/package.json
- examples/guard-angular/src/app/app.component.css
- examples/guard-angular/src/app/app.module.ts
- examples/guard-react/package-lock.json
- examples/guard-react/package.json
- examples/guard-react/src/App.tsx
- examples/guard-react/webpack.config.js
- examples/guard-vue2/package-lock.json
- examples/guard-vue2/package.json
- examples/guard-vue2/src/main.js
- examples/guard-vue2/src/views/Personal.vue
- examples/guard-vue3/package-lock.json
- examples/guard-vue3/package.json
- examples/guard-vue3/src/main.ts
- examples/guard-vue3/src/views/Personal.vue
- examples/guard/package-lock.json
- examples/guard/package.json
- examples/guard/src/App.tsx
- examples/guard/src/pages/Callback.tsx
- examples/guard/src/pages/Jump.tsx
- examples/guard/src/pages/Login.tsx
- examples/guard/src/pages/Personal.tsx
> feat: optimize codes

- .github/workflows/release.yml
- README-zh_CN.md
- README.md
- package-lock.json
- package.json
- scripts/oss.js
> feat: update oss

- .husky/pre-commit
- package-lock.json
- package.json
> feat: add husky

- README-zh_CN.md
- README.md
- examples/guard/src/config.ts
- packages/guard-angular/doc/README.md
- packages/guard-react/doc/README.md
- packages/guard-vue2/doc/README.md
- packages/guard-vue3/doc/README.md
- packages/guard/doc/README.md
- packages/guard/src/index.tsx
> chore: adjust public config and README.md

- examples/guard-angular/package-lock.json
- examples/guard-angular/package.json
- examples/guard-react/package-lock.json
- examples/guard-react/package.json
- examples/guard-vue2/package-lock.json
- examples/guard-vue2/package.json
- examples/guard-vue3/package-lock.json
- examples/guard-vue3/package.json
- examples/guard/package-lock.json
- examples/guard/package.json
- lerna.json
- packages/guard-angular/package-lock.json
- packages/guard-angular/package.json
- packages/guard-react/package-lock.json
- packages/guard-react/package.json
- packages/guard-vue2/package-lock.json
- packages/guard-vue2/package.json
- packages/guard-vue3/package-lock.json
- packages/guard-vue3/package.json
- packages/guard/package-lock.json
- packages/guard/package.json
> Chore adjust public config documents

- examples/guard-angular/package-lock.json
- examples/guard-angular/package.json
- examples/guard-angular/src/app/app.module.ts
- examples/guard-react/package-lock.json
- examples/guard-react/package.json
- examples/guard-react/src/App.tsx
- examples/guard-vue2/README.md
- examples/guard-vue2/package-lock.json
- examples/guard-vue2/package.json
- examples/guard-vue2/src/main.js
- examples/guard-vue3/package-lock.json
- examples/guard-vue3/package.json
- examples/guard-vue3/src/main.ts
- examples/guard/README.md
- examples/guard/package-lock.json
- examples/guard/package.json
- lerna.json
- packages/guard-angular/package-lock.json
- packages/guard-angular/package.json
- packages/guard-react/package-lock.json
- packages/guard-react/package.json
- packages/guard-vue2/package-lock.json
- packages/guard-vue2/package.json
- packages/guard-vue3/package-lock.json
- packages/guard-vue3/package.json
- packages/guard/package-lock.json
- packages/guard/package.json
- packages/guard/src/index.tsx
> Fix bug 20220813

- examples/guard-angular/package-lock.json
- examples/guard-angular/package.json
- examples/guard-react/package-lock.json
- examples/guard-react/package.json
- examples/guard-vue2/package-lock.json
- examples/guard-vue2/package.json
- examples/guard-vue3/package-lock.json
- examples/guard-vue3/package.json
- examples/guard/package-lock.json
- examples/guard/package.json
- examples/guard/src/config.ts
- examples/guard/src/pages/Jump.tsx
- examples/guard/src/pages/Login.tsx
- lerna.json
- package-lock.json
- packages/guard-angular/package-lock.json
- packages/guard-angular/package.json
- packages/guard-react/package-lock.json
- packages/guard-react/package.json
- packages/guard-vue2/package-lock.json
- packages/guard-vue2/package.json
- packages/guard-vue3/package-lock.json
- packages/guard-vue3/package.json
- packages/guard/package-lock.json
- packages/guard/package.json
- packages/guard/src/index.tsx
> fix: update logout function

- examples/guard-react/package-lock.json
- examples/guard-react/package.json
- examples/guard-react/src/pages/Login.tsx
> test: run example for version 5.0.3

- README-zh_CN.md
- README.md
> Chore update readme 20220921

- examples/guard-angular/README.md
- examples/guard-angular/src/app/app.module.ts
- examples/guard-nextjs/README.md
- examples/guard-nextjs/config.js
- examples/guard-react/README.md
- examples/guard-react/src/App.tsx
- examples/guard-vue2/README.md
- examples/guard-vue2/src/main.js
- examples/guard-vue3/README.md
- examples/guard-vue3/src/main.ts
- examples/guard/README.md
- examples/guard/src/config.ts
> doc(examples): update examples README

- examples/guard-vue3/modal/package-lock.json
- examples/guard-vue3/modal/package.json
- examples/guard-vue3/modal/src/main.ts
- examples/guard-vue3/normal/package-lock.json
- examples/guard-vue3/normal/package.json
- examples/guard/modal/embed.html
- examples/guard/normal/callback.html
- examples/guard/normal/embed.html
- examples/guard/normal/jump.html
- examples/guard/normal/personal.html
- lerna.json
- package-lock.json
- packages/guard-angular/package-lock.json
- packages/guard-angular/package.json
- packages/guard-react/package-lock.json
- packages/guard-react/package.json
- packages/guard-vue2/package-lock.json
- packages/guard-vue2/package.json
- packages/guard-vue3/package-lock.json
- packages/guard-vue3/package.json
- packages/guard/package-lock.json
- packages/guard/package.json
> fix(clickCloseable): upgrade @authing/react-ui-components

- packages/guard-angular/README.md
- packages/guard-angular/README.zh_CN.md
- packages/guard-react/README.md
- packages/guard-react/README.zh_CN.md
- packages/guard-react18/README.md
- packages/guard-react18/README.zh_CN.md
- packages/guard-vue2/README.md
- packages/guard-vue2/README.zh_CN.md
- packages/guard-vue3/README.md
- packages/guard-vue3/README.zh_CN.md
- packages/guard/README.md
- packages/guard/README.zh_CN.md
> chore: fix README.md

- README-zh_CN.md
- README.md
> chore: update README.md

- examples/guard-angular/modal/README.md
- examples/guard-angular/normal/README.md
- examples/guard-nextjs-react18/README.md
- examples/guard-nextjs/README.md
- examples/guard-react/modal/README.md
- examples/guard-react/normal/README.md
- examples/guard-react18/modal/README.md
- examples/guard-react18/normal/README.md
- examples/guard-vue2/modal/README.md
- examples/guard-vue2/normal/README.md
- examples/guard-vue3/modal/README.md
- examples/guard-vue3/normal/README.md
> chore: update README.md in examples

- lerna.json
- packages/guard-angular/package-lock.json
- packages/guard-angular/package.json
- packages/guard-react/package-lock.json
- packages/guard-react/package.json
- packages/guard-react18/package-lock.json
- packages/guard-react18/package.json
- packages/guard-shim-react18/package-lock.json
- packages/guard-shim-react18/package.json
- packages/guard-vue2/package-lock.json
- packages/guard-vue2/package.json
- packages/guard-vue3/package-lock.json
- packages/guard-vue3/package.json
- packages/guard/package-lock.json
- packages/guard/package.json
> Feat/guard update 4.1.1

- lerna.json
- packages/guard-angular/package-lock.json
- packages/guard-angular/package.json
- packages/guard-react/package-lock.json
- packages/guard-react/package.json
- packages/guard-react18/package-lock.json
- packages/guard-react18/package.json
- packages/guard-shim-react18/package-lock.json
- packages/guard-shim-react18/package.json
- packages/guard-vue2/package-lock.json
- packages/guard-vue2/package.json
- packages/guard-vue3/package-lock.json
- packages/guard-vue3/package.json
- packages/guard/package-lock.json
- packages/guard/package.json
> Feat/update guard 4.2.0

- examples/guard-react/normal/index.html
- examples/guard-react18/normal/package-lock.json
- examples/guard-react18/normal/package.json
- examples/guard-vue3/normal/package-lock.json
- examples/guard-vue3/normal/package.json
- lerna.json
- packages/guard-angular/package-lock.json
- packages/guard-angular/package.json
- packages/guard-react/package-lock.json
- packages/guard-react/package.json
- packages/guard-react18/package-lock.json
- packages/guard-react18/package.json
- packages/guard-shim-react18/package-lock.json
- packages/guard-shim-react18/package.json
- packages/guard-shim-react18/src/index.tsx
- packages/guard-shim-react18/src/types.ts
- packages/guard-vue2/package-lock.json
- packages/guard-vue2/package.json
- packages/guard-vue3/package-lock.json
- packages/guard-vue3/package.json
- packages/guard/package-lock.json
- packages/guard/package.json
- packages/guard/src/index.tsx
- packages/guard/src/types.ts
> feat: custom logout params

- examples/guard-nextjs-react18/config.ts
- examples/guard-nextjs-react18/package-lock.json
- examples/guard-nextjs-react18/package.json
- examples/guard-nextjs/package-lock.json
- examples/guard-nextjs/package.json
> test: run ssr examples

- examples/guard-react/normal/package-lock.json
- examples/guard-react/normal/package.json
- examples/guard-react/normal/src/App.css
- examples/guard-react/normal/src/pages/Embed.tsx
- examples/guard-react18/normal/package-lock.json
- examples/guard-react18/normal/package.json
- examples/guard-react18/normal/src/App.css
- examples/guard-react18/normal/src/pages/Embed.tsx
- lerna.json
- packages/guard-angular/package-lock.json
- packages/guard-angular/package.json
- packages/guard-react/package-lock.json
- packages/guard-react/package.json
- packages/guard-react18/package-lock.json
- packages/guard-react18/package.json
- packages/guard-shim-react18/package-lock.json
- packages/guard-shim-react18/package.json
- packages/guard-shim-react18/src/index.tsx
- packages/guard-shim-react18/src/types.ts
- packages/guard-vue2/package-lock.json
- packages/guard-vue2/package.json
- packages/guard-vue3/package-lock.json
- packages/guard-vue3/package.json
- packages/guard/package-lock.json
- packages/guard/package.json
- packages/guard/src/index.tsx
- packages/guard/src/types.ts
> feat: update Guard default style

- examples/guard-react18/modal/package-lock.json
- examples/guard-react18/modal/package.json
- examples/guard-react18/normal/package-lock.json
- examples/guard-react18/normal/package.json
- lerna.json
- packages/guard-angular/package-lock.json
- packages/guard-angular/package.json
- packages/guard-react/package-lock.json
- packages/guard-react/package.json
- packages/guard-react18/package-lock.json
- packages/guard-react18/package.json
- packages/guard-shim-react18/package-lock.json
- packages/guard-shim-react18/package.json
- packages/guard-shim-react18/src/index.tsx
- packages/guard-vue2/package-lock.json
- packages/guard-vue2/package.json
- packages/guard-vue3/package-lock.json
- packages/guard-vue3/package.json
- packages/guard/package-lock.json
- packages/guard/package.json
- packages/guard/src/index.tsx
> fix: set default style in normal mode

- examples/guard-react/normal/package-lock.json
- examples/guard-react/normal/package.json
- examples/guard-react18/normal/package-lock.json
- examples/guard-react18/normal/package.json
- examples/guard-react18/normal/src/App.tsx
- lerna.json
- packages/guard-angular/package-lock.json
- packages/guard-angular/package.json
- packages/guard-react/package-lock.json
- packages/guard-react/package.json
- packages/guard-react18/package-lock.json
- packages/guard-react18/package.json
- packages/guard-shim-react18/package-lock.json
- packages/guard-shim-react18/package.json
- packages/guard-vue2/package-lock.json
- packages/guard-vue2/package.json
- packages/guard-vue3/package-lock.json
- packages/guard-vue3/package.json
- packages/guard/package-lock.json
- packages/guard/package.json
> feat: login by scan qrcode with app

- examples/guard-react/normal/package-lock.json
- examples/guard-react/normal/package.json
- examples/guard-react18/normal/package-lock.json
- examples/guard-react18/normal/package.json
- examples/guard-vue2/normal/package-lock.json
- examples/guard-vue2/normal/package.json
- examples/guard-vue3/normal/package-lock.json
- examples/guard-vue3/normal/package.json
> test: run examples for version 5.1.3 🚀 

- lerna.json
- packages/guard-angular/package-lock.json
- packages/guard-angular/package.json
- packages/guard-react/package-lock.json
- packages/guard-react/package.json
- packages/guard-react18/package-lock.json
- packages/guard-react18/package.json
- packages/guard-shim-react18/package-lock.json
- packages/guard-shim-react18/package.json
- packages/guard-vue2/package-lock.json
- packages/guard-vue2/package.json
- packages/guard-vue3/package-lock.json
- packages/guard-vue3/package.json
- packages/guard/package-lock.json
- packages/guard/package.json
> fix push login value

- examples/guard-react18/normal/src/pages/TestGuard4.tsx
> chore: delete useless codes

- examples/guard-react/normal/src/pages/Embed.tsx
> test: run example for login error

- examples/guard-react/normal/package-lock.json
- examples/guard-react/normal/package.json
- examples/guard-react/normal/src/pages/Embed.tsx
- examples/guard-react18/normal/package-lock.json
- examples/guard-react18/normal/package.json
- examples/guard-react18/normal/src/pages/Embed.tsx
- lerna.json
- package-lock.json
- package.json
- packages/guard-angular/package-lock.json
- packages/guard-angular/package.json
- packages/guard-react/package-lock.json
- packages/guard-react/package.json
- packages/guard-react18/package-lock.json
- packages/guard-react18/package.json
- packages/guard-shim-react18/package-lock.json
- packages/guard-shim-react18/package.json
- packages/guard-vue2/package-lock.json
- packages/guard-vue2/package.json
- packages/guard-vue3/package-lock.json
- packages/guard-vue3/package.json
- packages/guard/package-lock.json
- packages/guard/package.json
> fix login error callback, upgrade react ui components to 4.3.11
